org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Configuration cache disabled because architectury-loom isn't compatible with it.
org.gradle.configuration-cache=false

# Parchment mappings for better code readability
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=1.20.1-47.4.20
forge_version_range=[47,)
forge_loader_version_range=[47,)

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.92.9+1.20.1

# Architectury
architectury_version=9.2.14
enabled_platforms=fabric,forge

## Mod Properties
mod_id=enoughfolders
mod_name=Enough Folders
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.vodmordia.enoughfolders
mod_authors=vodmordia
mod_description=Enough Folders allows you to organize your JEI items into folders for better organization.

# Dependencies
mc_version=1.20.1
jei_version=15.20.0.130
