org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Configuration cache disabled because architectury-loom isn't compatible with it.
org.gradle.configuration-cache=false

# Parchment mappings for better code readability
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.145
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Architectury
architectury_version=13.0.8
enabled_platforms=neoforge

# Fabric loader is referenced by architectury common for the @Environment annotation
fabric_loader_version=0.16.5

## Mod Properties
mod_id=enoughfolders
mod_name=Enough Folders
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=com.vodmordia.enoughfolders
mod_authors=vodmordia
mod_description=Enough Folders allows you to organize your JEI items into folders for better organization.

# Dependencies
mc_version=1.21.1
jei_version=19.21.0.247
